# Generated by Django 5.2.16 on 2026-07-25 20:56

import apps.candidates.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='nom complet')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telephone')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='localisation')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='titre professionnel')),
                ('total_experience_years', models.FloatField(default=0.0, verbose_name='experience totale (annees)')),
                ('highest_education', models.IntegerField(choices=[(0, 'Sans exigence'), (1, 'Baccalaureat'), (3, 'Bac+3 / Licence'), (5, 'Bac+5 / Master'), (8, 'Doctorat')], default=0, verbose_name='plus haut diplome')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='consentement recueilli le')),
                ('retention_until', models.DateField(blank=True, null=True, verbose_name="conservation jusqu'au")),
            ],
            options={
                'verbose_name': 'candidat',
                'verbose_name_plural': 'candidats',
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['email'], name='candidates__email_188e48_idx'), models.Index(fields=['retention_until'], name='candidates__retenti_56a690_idx')],
            },
        ),
        migrations.CreateModel(
            name='CVDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.candidates.models.cv_upload_path, verbose_name='fichier')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('extracting', 'Extraction en cours'), ('parsing', 'Structuration en cours'), ('done', 'Termine'), ('failed', 'Echec')], default='pending', max_length=12)),
                ('method', models.CharField(blank=True, choices=[('text', 'Texte natif (PyMuPDF)'), ('docx', 'DOCX (python-docx)'), ('vision', 'Vision (Qwen3-VL)'), ('hybrid', 'Texte + vision')], max_length=8)),
                ('error', models.TextField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('quality', models.JSONField(blank=True, default=dict)),
                ('extraction_started_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_finished_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceSpan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('text', models.TextField()),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('char_start', models.PositiveIntegerField(blank=True, null=True)),
                ('char_end', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='candidates.cvdocument')),
            ],
            options={
                'verbose_name': 'preuve',
                'verbose_name_plural': 'preuves',
                'ordering': ('page', 'char_start'),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('degree', models.CharField(max_length=200, verbose_name='diplome')),
                ('field_of_study', models.CharField(blank=True, max_length=200, verbose_name='specialite')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='etablissement')),
                ('level', models.IntegerField(choices=[(0, 'Sans exigence'), (1, 'Baccalaureat'), (3, 'Bac+3 / Licence'), (5, 'Bac+5 / Master'), (8, 'Doctorat')], default=0)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='candidates.candidate')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='candidates.evidencespan')),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'formations',
                'ordering': ('-graduation_year',),
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('name', models.CharField(max_length=200, verbose_name='certification')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='organisme')),
                ('obtained_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='candidates.candidate')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='candidates.evidencespan')),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
                'ordering': ('-obtained_year',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('title', models.CharField(max_length=200, verbose_name='poste')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='entreprise')),
                ('location', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fin (vide si en cours)')),
                ('description', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidate')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='candidates.evidencespan')),
            ],
            options={
                'verbose_name': 'experience',
                'verbose_name_plural': 'experiences',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('received', 'Recue'), ('screening', 'Pre-selection'), ('phone', 'Entretien telephonique'), ('technical', 'Entretien technique'), ('final', 'Entretien final'), ('offer', 'Proposition'), ('hired', 'Recrute'), ('rejected', 'Ecarte'), ('withdrawn', 'Desistement')], default='received', max_length=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, verbose_name='motif de la decision')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='candidates.cvdocument')),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ('-applied_at',),
                'indexes': [models.Index(fields=['offer', 'stage'], name='candidates__offer_i_f0a1db_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'offer'), name='unique_application_per_offer')],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('name', models.CharField(max_length=120, verbose_name='competence')),
                ('normalized_name', models.CharField(db_index=True, max_length=120)),
                ('esco_uri', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('declared', 'Declaree (section competences)'), ('inferred', "Deduite d'une experience"), ('ontology', "Deduite par l'ontologie")], default='declared', max_length=10)),
                ('years', models.FloatField(default=0.0, verbose_name='annees de pratique')),
                ('last_used_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidates.candidate')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='candidates.evidencespan')),
            ],
            options={
                'verbose_name': 'competence du candidat',
                'verbose_name_plural': 'competences du candidat',
                'ordering': ('-years', 'name'),
                'constraints': [models.UniqueConstraint(fields=('candidate', 'normalized_name'), name='unique_skill_per_candidate')],
            },
        ),
        migrations.CreateModel(
            name='CandidateLanguage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('language', models.CharField(max_length=60, verbose_name='langue')),
                ('level', models.CharField(choices=[('A1', 'A1 — Debutant'), ('A2', 'A2 — Elementaire'), ('B1', 'B1 — Intermediaire'), ('B2', 'B2 — Intermediaire superieur'), ('C1', 'C1 — Avance'), ('C2', 'C2 — Maitrise'), ('NAT', 'Langue maternelle')], default='B1', max_length=3)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='candidates.candidate')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='candidates.evidencespan')),
            ],
            options={
                'verbose_name': 'langue',
                'verbose_name_plural': 'langues',
                'constraints': [models.UniqueConstraint(fields=('candidate', 'language'), name='unique_language_per_candidate')],
            },
        ),
    ]
