# Generated by Django 5.2.16 on 2026-07-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencespan',
            name='match_ratio',
            field=models.FloatField(default=0.0, verbose_name='qualite de la correspondance'),
        ),
    ]
