# Generated by Django 5.2.16 on 2026-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('recruiter', 'Recruteur'), ('hiring_manager', 'Manager operationnel'), ('viewer', 'Lecture seule'), ('agent', "Agent d'orchestration")], default='recruiter', max_length=20),
        ),
    ]
