# Generated by Django 5.2.16 on 2026-08-04 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0003_backfill_retention_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('done', 'Terminee'), ('failed', 'Echouee'), ('budget', 'Arretee par le budget'), ('disabled', 'Agent desactive')], default='running', max_length=10)),
                ('trigger', models.CharField(choices=[('manual', 'Lancee a la main'), ('upload', "Depot d'un CV"), ('schedule', 'Tache periodique')], default='manual', max_length=10)),
                ('applications_seen', models.PositiveIntegerField(default=0, verbose_name='dossiers examines')),
                ('applications_processed', models.PositiveIntegerField(default=0, verbose_name='dossiers traites')),
                ('steps_done', models.PositiveIntegerField(default=0, verbose_name='etapes executees')),
                ('steps_failed', models.PositiveIntegerField(default=0, verbose_name='etapes en echec')),
                ('recommendations_made', models.PositiveIntegerField(default=0, verbose_name='recommandations')),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "execution de l'agent",
                'verbose_name_plural': "executions de l'agent",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_stage', models.CharField(max_length=20, verbose_name='etape proposee')),
                ('rationale', models.TextField(verbose_name='motif propose')),
                ('score_at_time', models.FloatField(default=0.0)),
                ('threshold_at_time', models.FloatField(default=0.0)),
                ('engine_version', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Suivie'), ('rejected', 'Ecartee par le recruteur'), ('stale', 'Perimee')], default='pending', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='candidates.application')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_recommendations', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='agent.agentrun')),
            ],
            options={
                'verbose_name': 'recommandation',
                'verbose_name_plural': 'recommandations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['-created_at'], name='agent_agent_created_7b73d3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status'], name='agent_agent_status_6aab4c_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['application', '-created_at'], name='agent_recom_applica_ccf33a_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['status'], name='agent_recom_status_dc5565_idx'),
        ),
    ]
