# Generated by Django 5.2.16 on 2026-07-25 20:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='intitule')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='departement')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='localisation')),
                ('remote_policy', models.CharField(choices=[('onsite', 'Sur site'), ('hybrid', 'Hybride'), ('remote', 'Teletravail total')], default='hybrid', max_length=10, verbose_name='teletravail')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('internship', 'Stage'), ('apprenticeship', 'Alternance'), ('freelance', 'Freelance')], default='cdi', max_length=16, verbose_name='contrat')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='salaire min')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='salaire max')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('experience_min_years', models.PositiveSmallIntegerField(default=0, verbose_name='experience min (annees)')),
                ('experience_max_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='experience max (annees)')),
                ('education_level', models.IntegerField(choices=[(0, 'Sans exigence'), (1, 'Baccalaureat'), (3, 'Bac+3 / Licence'), (5, 'Bac+5 / Master'), (8, 'Doctorat')], default=0, verbose_name="niveau d'etudes")),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='date limite')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouverte'), ('paused', 'Suspendue'), ('closed', 'Cloturee')], default='draft', max_length=10)),
                ('scoring_weights', models.JSONField(blank=True, default=dict, help_text="Surcharge la ponderation par defaut. Laisser vide pour l'heriter.", verbose_name='ponderation du score')),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "offre d'emploi",
                'verbose_name_plural': "offres d'emploi",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobLanguage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=60, verbose_name='langue')),
                ('min_level', models.CharField(choices=[('A1', 'A1 — Debutant'), ('A2', 'A2 — Elementaire'), ('B1', 'B1 — Intermediaire'), ('B2', 'B2 — Intermediaire superieur'), ('C1', 'C1 — Avance'), ('C2', 'C2 — Maitrise'), ('NAT', 'Langue maternelle')], default='B2', max_length=3, verbose_name='niveau minimum')),
                ('is_required', models.BooleanField(default=True, verbose_name='obligatoire')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'langue attendue',
                'verbose_name_plural': 'langues attendues',
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='competence')),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('esco_uri', models.URLField(blank=True)),
                ('requirement', models.CharField(choices=[('required', 'Obligatoire'), ('preferred', 'Souhaitee')], default='required', max_length=10)),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)], verbose_name='poids relatif')),
                ('min_years', models.PositiveSmallIntegerField(default=0, verbose_name='anciennete min')),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'competence attendue',
                'verbose_name_plural': 'competences attendues',
                'ordering': ('requirement', '-weight', 'name'),
            },
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['status', '-created_at'], name='jobs_joboff_status_bdce53_idx'),
        ),
        migrations.AddConstraint(
            model_name='joblanguage',
            constraint=models.UniqueConstraint(fields=('offer', 'language'), name='unique_language_per_offer'),
        ),
        migrations.AddConstraint(
            model_name='jobskill',
            constraint=models.UniqueConstraint(fields=('offer', 'normalized_name'), name='unique_skill_per_offer'),
        ),
    ]
