# Generated by Django 5.2.16 on 2026-07-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='required_certifications',
            field=models.JSONField(blank=True, default=list, help_text='Liste de noms, ex. ["AWS Solutions Architect"]. Vide = critere non applicable.', verbose_name='certifications exigees'),
        ),
    ]
