# Generated by Django 5.2.16 on 2026-07-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joboffer_required_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='blind_screening',
            field=models.BooleanField(default=False, help_text="Exclut la localisation du calcul du score et masque les employeurs dans l'analyse redigee. La politique appartient a l'offre, non au recruteur : le score doit etre identique pour tous ceux qui la consultent.", verbose_name="screening a l'aveugle"),
        ),
    ]
