# Generated by Django 5.2.16 on 2026-07-25 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('cv_uploaded', 'CV depose'), ('cv_parsed', 'CV analyse'), ('score_computed', 'Score calcule'), ('score_overridden', 'Score corrige manuellement'), ('stage_changed', 'Etape modifiee'), ('candidate_viewed', 'Candidat consulte'), ('data_exported', 'Donnees exportees'), ('data_purged', 'Donnees purgees')], db_index=True, max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entree d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx')],
            },
        ),
    ]
