# Generated by Django 5.2.16 on 2026-07-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('cv_uploaded', 'CV depose'), ('cv_parsed', 'CV analyse'), ('score_computed', 'Score calcule'), ('score_overridden', 'Score corrige manuellement'), ('stage_changed', 'Etape modifiee'), ('candidate_viewed', 'Candidat consulte'), ('data_exported', 'Donnees exportees'), ('data_purged', 'Donnees purgees'), ('candidates_merged', 'Dossiers fusionnes')], db_index=True, max_length=32),
        ),
    ]
