# Generated by Django 5.2.16 on 2026-08-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agent_watched_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('cv_uploaded', 'CV depose'), ('cv_parsed', 'CV analyse'), ('score_computed', 'Score calcule'), ('score_overridden', 'Score corrige manuellement'), ('stage_changed', 'Etape modifiee'), ('candidate_viewed', 'Candidat consulte'), ('data_exported', 'Donnees exportees'), ('data_purged', 'Donnees purgees'), ('candidates_merged', 'Dossiers fusionnes'), ('bias_monitored', 'Controle de biais'), ('agent_ran', "Execution de l'agent"), ('agent_recommended', "Recommandation de l'agent"), ('agent_watched', "Veille de l'agent"), ('message_sent', 'Message envoye'), ('message_logged', 'Echange consigne'), ('consent_recorded', 'Consentement enregistre')], db_index=True, max_length=32),
        ),
    ]
