# Generated by Django 5.2.16 on 2026-07-25 22:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='score global')),
                ('engine_version', models.CharField(max_length=16)),
                ('weights_used', models.JSONField(default=dict)),
                ('breakdown', models.JSONField(default=dict)),
                ('skill_matches', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('semantic_used', models.BooleanField(default=False, verbose_name='rapprochement semantique disponible')),
                ('compute_ms', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True)),
                ('explanation_prompt_id', models.CharField(blank=True, max_length=64)),
                ('explanation_prompt_version', models.CharField(blank=True, max_length=16)),
                ('explanation_model', models.CharField(blank=True, max_length=120)),
                ('overridden_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='score corrige')),
                ('override_reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='candidates.application')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'score de compatibilite',
                'verbose_name_plural': 'scores de compatibilite',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['application', '-created_at'], name='matching_ma_applica_3ba4e9_idx'), models.Index(fields=['-overall'], name='matching_ma_overall_db0e8b_idx')],
            },
        ),
    ]
