# Generated by Django 5.2.16 on 2026-07-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscore',
            name='blind',
            field=models.BooleanField(default=False, help_text="Localisation exclue du calcul, employeurs masques dans l'analyse.", verbose_name="calcule en screening a l'aveugle"),
        ),
    ]
