# Generated by Django 5.2.16 on 2026-07-27 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_evidencespan_match_ratio'),
        ('matching', '0002_matchscore_blind'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('theme', models.CharField(blank=True, max_length=120, verbose_name='sujet')),
                ('intent', models.CharField(choices=[('verification', 'Verifier un acquis annonce'), ('exploration', "Sonder un ecart avec l'offre"), ('mise_en_situation', 'Mise en situation')], default='verification', max_length=20, verbose_name='intention')),
                ('cv_claim', models.TextField(blank=True, verbose_name='affirmation visee')),
                ('question', models.TextField()),
                ('expected_signals', models.TextField(blank=True, verbose_name="ce qu'une bonne reponse contient")),
                ('prompt_id', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=16)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='candidates.application')),
            ],
            options={
                'verbose_name': "question d'entretien",
                'verbose_name_plural': "questions d'entretien",
                'ordering': ('position',),
                'indexes': [models.Index(fields=['application', 'position'], name='matching_in_applica_76f226_idx')],
            },
        ),
    ]
