# Generated by Django 5.2.16 on 2026-08-05 08:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0003_backfill_retention_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('call', 'Appel telephonique'), ('other', 'Autre')], max_length=10)),
                ('granted', models.BooleanField(default=True, verbose_name='accorde')),
                ('source', models.CharField(choices=[('form', 'Formulaire de candidature'), ('verbal', 'Accord verbal, note par un recruteur'), ('imported', "Repris d'un systeme anterieur"), ('withdrawn', 'Retrait demande par le candidat')], default='form', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='candidates.candidate')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consentement',
                'verbose_name_plural': 'consentements',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['candidate', 'channel', '-created_at'], name='outreach_co_candida_6a19d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('call', 'Appel telephonique'), ('other', 'Autre')], max_length=10)),
                ('direction', models.CharField(choices=[('out', 'Vers le candidat'), ('in', 'Recu du candidat')], default='out', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoye'), ('failed', "Echec d'envoi"), ('logged', 'Consigne')], default='draft', max_length=6)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='objet')),
                ('body', models.TextField(verbose_name='corps')),
                ('template_id', models.CharField(blank=True, max_length=40)),
                ('template_version', models.CharField(blank=True, max_length=16)),
                ('prompt_id', models.CharField(blank=True, max_length=40)),
                ('prompt_version', models.CharField(blank=True, max_length=16)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='candidates.application')),
                ('drafted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_drafted', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['application', '-created_at'], name='outreach_me_applica_cf7a5c_idx'), models.Index(fields=['status'], name='outreach_me_status_7d313c_idx'), models.Index(fields=['channel'], name='outreach_me_channel_e7bbcc_idx')],
            },
        ),
    ]
