# Generated by Django 5.2.16 on 2026-07-29 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_joboffer_blind_screening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterQuery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('filters', models.JSONField(default=dict)),
                ('rejected_criteria', models.JSONField(blank=True, default=list)),
                ('matched_ids', models.JSONField(blank=True, default=list)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('answer', models.TextField(blank=True)),
                ('filter_prompt_version', models.CharField(blank=True, max_length=16)),
                ('answer_prompt_version', models.CharField(blank=True, max_length=16)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_queries', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_queries', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'question de recruteur',
                'verbose_name_plural': 'questions de recruteur',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['offer', '-created_at'], name='assistant_r_offer_i_4c259e_idx')],
            },
        ),
    ]
