# Generated by Django 5.2.16 on 2026-07-25 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInvocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('chat', 'Texte'), ('vision', 'Vision'), ('embedding', 'Embedding')], default='chat', max_length=16)),
                ('purpose', models.CharField(db_index=True, max_length=64, verbose_name='usage')),
                ('prompt_id', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=16)),
                ('model', models.CharField(max_length=120)),
                ('base_url', models.CharField(blank=True, max_length=200)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('temperature', models.FloatField(default=0.0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('ok', 'Succes'), ('error', 'Erreur')], default='ok', max_length=8)),
                ('error', models.TextField(blank=True)),
                ('subject_type', models.CharField(blank=True, max_length=64)),
                ('subject_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'appel IA',
                'verbose_name_plural': 'appels IA',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['purpose', '-created_at'], name='ai_aiinvoca_purpose_a4f3a8_idx'), models.Index(fields=['subject_type', 'subject_id'], name='ai_aiinvoca_subject_5bd809_idx')],
            },
        ),
    ]
