# Generated by Django 5.2.16 on 2026-07-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinvocation',
            name='finish_reason',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='aiinvocation',
            name='thinking',
            field=models.BooleanField(default=False, verbose_name='raisonnement actif'),
        ),
    ]
